# Generated by Django 5.2 on 2026-06-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', '交通費'), ('entertainment', '娯楽'), ('utilities', '光熱費'), ('salary', '給料'), ('other', 'その他')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=10)),
                ('amount', models.IntegerField()),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
